module.exports = [
    'Call options allow the holder to buy the asset at a stated price within a specific timeframe.',
    'Options grant the trader the right, but not the obligation, to buy or sell shares at a specified price known as a strike price.',
    'Put options allow the holder to sell the asset at a stated price within a specific timeframe.',
    'A strike price is the price at which a put or call option can be exercised. When an option is exercised, the right specified by the options contract is put into effect.',
    'Options contracts usually represent 100 shares of the underlying security. Buyers will pay a premium fee to purchase a contract. Sellers will receive the premium fee.',
    'Options traders typically use five risk indicators known as the greeks. The indicators are delta, gamma, theta, vega, and rho. ',
    'The expiration date for listed stock options is normally the third Friday of the contract Month.',
    'Options contracts do not represent ownership in a company',
    'Options prices are known as premiums. They are composed of the sum of its intrinsic and time value. Intrinsic value is the price difference between the current stock price and the strike price. Time value is determined by the remaining time until the options contract expires.',
    'In the money is an expression relating to intrinsic value.   An option that is in the money has value in a strike price that is favorable in comparison to the market price of the underlying asset. A call option is in the money if the market price of the underlying stock is above the strike price. A put option is in the money if the market price is below the strike price.',
    'Out of the money is an expression relating to intrinsic value. An option that is out of the money only derives value from its extrinsic value. An out of the money call option has a strike price that is higher than the underlying assets market value. An out of the money put option has a strike price that is lower than the market price of the underlying asset.',
    'Volatility is how likely the market is to change rapidly and unpredictably. In most cases, the higher the volatility the more risky the investment is.',
    'A long position in options trading is when the investor buys a call or put option. A short position is when the investor sells, or writes, a call or put option.',
    'Options traders can profit from buying and selling options contracts. Options contracts do not represent ownership within a company. Traders can buy or sell options contracts without actually owning any stocks.',
    'An owner of a call or put is not obligated to exercise his right to buy or sell. This is only the case if the trader buys a call or put.',
    'A bull put spread is when a trader sells a put at a higher strike price while simultaneously purchasing a put at a lower strike price. The traders profit is limited to the premium received. Profit is only realized if the stock price is at or above the strike price of the sold put.',
    'A bear put spread is when a trader buys a put at a higher strike price while simultaneously selling a put at a lower strike sprice. The trader can only profit if the underlying stock decreases in price.  ',
    'A covered call is an options strategy where the investor sells a call option for stock they own. The strategy is called a covered call because if the underlying stocks price increases rapidly, the investors short call option is covered by their long stock position.',
    'A married put is an options strategy where the investor purchases shares of stock and simultaneously purchases put options equivalent to the number of shares purchased. The holder of the put option has the right to sell the stock at the strike price. This protects the investor in case the stock price falls. ',
    'A credit spread is an options strategy where the investor sells an option with a high premium while simultaneously purchasing an option with a lower premium. This results in a portion of the premium being credited, or paid, to the investor. This strategy is primarily used to generate income or profits. ',
    'A debit spread is an options strategy where the investor buys an option with a high premium while simultaneously selling an option with a lower premium. This results in a portion of the premium being debited, or paid, from the investor. This strategy is primarily used to reduce the cost associated with a long options position.',
    'A straddle is an options strategy where the investor buys a call option and a put option at the same time with the same strike price and expiration date. Traders can profit from this strategy as long as the underlying stock price rises or falls from the strike price set during the purchase of the options. The stock must rise or fall by an amount that is more than the total cost of the premium paid to enter the options position.',
    'It is possible to sell a put option without owning any shares of the underlying stock. This is called selling naked, and the strategy technically has unlimited risk.',
    'A strangle is an options strategy where the investor maintains a position in both a call and a put option with different strike prices, but with the same expiration date and underlying stock. This strategy is reliable if the trader believes there will be a large price movement in the future whether up or down. ',
    'Options traders use several risk indicators known as the greeks. One such greek, Delta, represents the rate of change between the options price and the underlying assets price. Another common usage of an options delta is to determine the probability the option will expire in the money. ',
    'Options traders use several risk indicators known as the greeks. One such greek, Theta, represents the rate of change between the option price and time. It can be used to determine the options time decay. ',
    'Options traders use several risk indicators known as the greeks. One such greek, Gamma, represents the rate of change between an options delta and the underlying assets price. Basically, gamma indicates the amount delta would change given a dollar move in the underlying stocks price. ',
    'Options traders use several risk indicators known as the greeks. One such greek, Vega, represents the rate of change between an options value and the underlying assets implied volatility. This is the options sensitivity to volatility. ',
    'Options traders use several risk indicators known as the greeks. One such greek, Rho, represents the rate of change between an options value and a one percent change in the interest rate. Rho is useful for determining how sensitive an option is interest rates. ',
    'Options contracts are not just monthly. They can also be weekly.',
    'An iron condor is an options strategy created with four options consisting of two puts, one long and one short, and two calls, one long and one short. These have four strike prices all with the same expiration date. The goal is to profit from low volatility in the underlying asset. You will earn the maximum profit when the underlying asset closes between the middle strike prices at expiration.',
    'Butterfly spreads use four option contracts with the same expiration. These have three different strike prices. A higher strike price, an at-the-money strike price, and a lower strike price.',
    'As a put option buyer, you expect the underlying stock’s price to fall.',
    'As a call option buyer, you expect the underlying stocks price to rise.',
    'As a put option seller, you expect the underlying stocks price to rise.',
    'As a call option seller, you expect the underlying stocks price to fall.',
    'As an options trader, you are not required to buy or sell the underlying asset unless you are exercised.',
    'An exchange-traded fund, also known as an ETF, is a collection of assets such as stocks and bonds. You can sell options for some ETFs.',
    'American options are subject to “early exercise”; this means they can be exercised at any time prior to expiration.', 
    'Implied volatility typically increases in bear markets and decreases in bull markets.', 
    'Implied volatility is a metric that measures the market’s likelihood of change. The volatility index, also known as the VIX, is a real time index that represents the market’s expectation of volatility within the next thirty days.',
    'Implied volatility is a deciding factor in the pricing of options contracts. Options with high implied volatility will have higher premiums and options with low implied volatility will have lower premiums.',
    'Many options contracts have what is known as an unlimited downside. This means that if the market goes against what you believed when you entered your options position, you may face a rather large loss. This is only the case if you sell an options.', 
    'If you purchase an options, your loss is limited to the price of the option. Your potential profit is technically unlimited.', 
    'Options contracts are often used to hedge stock positions. For example, buying a put can hedge  a long position. In comparison, buying a call can hedge a short position.', 
    'Options contracts are typically viewed as more risky than simply trading stocks. This is because many options contracts and strategies have unlimited risk.', 
    'Options contracts are known as derivatives. In finance, derivatives are products whose value is determined be an underlying asset.', 
    'Many traders try to limit the risk associated with options by modeling them mathematically. Once such model, is the Black Scholes Model. The model estimates the variation over time of financial instruments such as stocks or futures.', 
    'Out of the money options are less expensive than at the money options and in the money options',
    'Put options are available on more than just stocks. You can get them on indexes, commodities, and even currencies.', 
];